# Generated by Django 5.1.3 on 2024-11-21 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='adultomayor',
            name='telefono',
            field=models.IntegerField(max_length=20),
        ),
        migrations.AlterField(
            model_name='adultomayor',
            name='comuna',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.comuna'),
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut_instructor', models.CharField(max_length=20, unique=True)),
                ('p_nombre', models.CharField(max_length=20)),
                ('s_nombre', models.CharField(blank=True, max_length=20)),
                ('p_apellido', models.CharField(max_length=20)),
                ('s_apellido', models.CharField(blank=True, max_length=20)),
                ('fecha_nacimiento', models.DateField()),
                ('correo_electronico', models.EmailField(max_length=100)),
                ('telefono', models.IntegerField(max_length=20)),
                ('comuna', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.comuna')),
                ('genero', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.genero')),
            ],
        ),
    ]
