# Generated by Django 5.1.3 on 2024-11-21 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_adultomayor_comuna'),
    ]

    operations = [
        migrations.AddField(
            model_name='adultomayor',
            name='comuna',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.comuna'),
        ),
    ]
