# Generated by Django 5.1.3 on 2024-12-02 22:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_adultomayor_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taller',
            name='prom_evalua_taller',
        ),
        migrations.AddField(
            model_name='taller',
            name='integrantes',
            field=models.ManyToManyField(related_name='talleres', to='core.adultomayor'),
        ),
        migrations.AlterField(
            model_name='adultomayor',
            name='telefono',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='adultomayor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='adulto_mayor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Instructor',
        ),
    ]
