# Generated by Django 5.1.3 on 2024-12-03 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_taller_prom_evalua_taller_taller_integrantes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taller',
            name='integrantes',
            field=models.ManyToManyField(blank=True, related_name='talleres_inscritos', to='core.adultomayor'),
        ),
    ]
