# Generated by Django 5.1.3 on 2024-12-03 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_taller_integrantes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taller',
            name='integrantes',
        ),
        migrations.AddField(
            model_name='taller',
            name='integrantes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
