# Generated by Django 5.1.3 on 2024-12-03 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_taller_integrantes_taller_integrantes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taller',
            name='integrantes',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
